settings:
  default_form_file_limit: '22 MB'
html_editor:
  tidy: true
  disabled: true
file:
  make_unused_managed_files_temporary: true
  delete_temporary_managed_files: true
  file_public: true
  file_private_redirect: true
  default_max_filesize: '22 MB'
